- hosts: all
  name: create ec2 instance
  connection: local
  vars:
    base_ami: unknown
    security_group: cp-ssh-only
    instance_type: unknown
    key_pair: rome-master
    ami_inventory_file: ami-build
    instance_id_file: /tmp/ami-boongle-instance.tmp
    instance_name: unknown
    subnet_id: unknown
  tasks:
  - local_action: 
      module: ec2
      keypair: "{{key_pair}}"
      instance_type: "{{instance_type}}"
      image: "{{base_ami}}"
      group: "{{security_group}}"
      wait: yes
      instance_tags: '{"Name":"{{instance_name}}"}' 
      vpc_subnet_id: "{{subnet_id}}"
      volumes:
      - device_name: /dev/sda1
        volume_size: 30
    register: ec2
  - local_action: shell echo '{{ami_inventory_file}}'
  - local_action: shell echo '[ami-build]\n{{item.public_ip}}' > {{ami_inventory_file}}
    with_items: ec2.instances
  - local_action: wait_for host={{item.public_dns_name}} port=22
                  delay=60 timeout=900 state=started
    with_items: ec2.instances
  - local_action: shell echo '{{item.id}}' > {{instance_id_file}}
    with_items: ec2.instances
